Repository COOL-EWHA/devook-web, pull requests merged in 2022-03, with the labels that each got.

#88 [fix] 원글 읽기 버튼 클릭시 새 창으로 열리게끔 수정
  src/components/bookmarks/DetailCard.tsx
Labels: bug

#93 [개선] 모바일앱 로그인유지 관련 로직 개선
  src/lib/api/auth.ts
  src/lib/hooks/auth.ts
Labels: enhancement

#95 [Feature] 모바일앱 장치 등록, 삭제 관련 로직 추가
  src/interfaces/index.ts
  src/lib/hooks/auth.ts
  src/lib/store/auth.ts
Labels: feature
